--- #YAML:1.0
name:                Digest-SHA2
version:             1.1.1
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Digest::base:                  1.00
    MIME::Base64:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Julius C. Duque {jcduque}{at}{lycos}{dot}{com}
